// Mock data for SecYourFlow demo
// This simulates real data that would come from PostgreSQL

import {
    DashboardStats,
    RiskTrend,
    VulnerabilitySeverityDistribution,
    TopRiskyAsset,
    ComplianceOverview,
    RecentActivity,
    ExploitedVulnerability,
    Asset,
    Vulnerability,
} from "@/types";

export const mockDashboardStats: DashboardStats = {
    totalAssets: 1247,
    criticalAssets: 89,
    totalVulnerabilities: 3842,
    criticalVulnerabilities: 127,
    highVulnerabilities: 456,
    mediumVulnerabilities: 1823,
    lowVulnerabilities: 1436,
    exploitedVulnerabilities: 23,
    cisaKevCount: 18,
    overallRiskScore: 72.4,
    complianceScore: 78.3,
    openVulnerabilities: 2156,
    fixedThisMonth: 312,
    meanTimeToRemediate: 14.5,
};

export const mockRiskTrends: RiskTrend[] = [
    { date: "Jan 1", riskScore: 85.2, criticalVulns: 156, highVulns: 520 },
    { date: "Jan 8", riskScore: 82.1, criticalVulns: 148, highVulns: 498 },
    { date: "Jan 15", riskScore: 78.5, criticalVulns: 139, highVulns: 475 },
    { date: "Jan 22", riskScore: 75.8, criticalVulns: 132, highVulns: 462 },
    { date: "Jan 29", riskScore: 73.2, criticalVulns: 128, highVulns: 458 },
    { date: "Feb 5", riskScore: 72.4, criticalVulns: 127, highVulns: 456 },
];

export const mockSeverityDistribution: VulnerabilitySeverityDistribution[] = [
    { severity: "CRITICAL", count: 127, percentage: 3.3 },
    { severity: "HIGH", count: 456, percentage: 11.9 },
    { severity: "MEDIUM", count: 1823, percentage: 47.4 },
    { severity: "LOW", count: 1436, percentage: 37.4 },
];

export const mockTopRiskyAssets: TopRiskyAsset[] = [
    {
        id: "1",
        name: "prod-db-master-01",
        type: "DATABASE",
        criticality: "CRITICAL",
        vulnerabilityCount: 47,
        criticalVulnCount: 8,
        riskScore: 94.2,
    },
    {
        id: "2",
        name: "api-gateway-prod",
        type: "APPLICATION",
        criticality: "CRITICAL",
        vulnerabilityCount: 38,
        criticalVulnCount: 5,
        riskScore: 89.7,
    },
    {
        id: "3",
        name: "aws-ec2-payments",
        type: "CLOUD_INSTANCE",
        criticality: "CRITICAL",
        vulnerabilityCount: 52,
        criticalVulnCount: 7,
        riskScore: 87.3,
    },
    {
        id: "4",
        name: "k8s-node-prod-12",
        type: "CONTAINER",
        criticality: "HIGH",
        vulnerabilityCount: 29,
        criticalVulnCount: 4,
        riskScore: 82.1,
    },
    {
        id: "5",
        name: "dc1-fw-core-01",
        type: "NETWORK_DEVICE",
        criticality: "HIGH",
        vulnerabilityCount: 18,
        criticalVulnCount: 3,
        riskScore: 78.9,
    },
];

export const mockComplianceOverview: ComplianceOverview[] = [
    {
        frameworkId: "1",
        frameworkName: "ISO 27001:2022",
        totalControls: 93,
        compliant: 72,
        nonCompliant: 8,
        partiallyCompliant: 10,
        notAssessed: 3,
        compliancePercentage: 77.4,
    },
    {
        frameworkId: "2",
        frameworkName: "NIST CSF 2.0",
        totalControls: 108,
        compliant: 89,
        nonCompliant: 5,
        partiallyCompliant: 11,
        notAssessed: 3,
        compliancePercentage: 82.4,
    },
    {
        frameworkId: "3",
        frameworkName: "PCI DSS 4.0",
        totalControls: 64,
        compliant: 48,
        nonCompliant: 6,
        partiallyCompliant: 8,
        notAssessed: 2,
        compliancePercentage: 75.0,
    },
    {
        frameworkId: "4",
        frameworkName: "SOC 2 Type II",
        totalControls: 117,
        compliant: 98,
        nonCompliant: 4,
        partiallyCompliant: 12,
        notAssessed: 3,
        compliancePercentage: 83.8,
    },
];

export const mockRecentActivities: RecentActivity[] = [
    {
        id: "1",
        action: "Vulnerability remediated",
        entityType: "vulnerability",
        entityName: "CVE-2024-21762",
        userName: "Sarah Chen",
        timestamp: new Date(Date.now() - 1000 * 60 * 5),
    },
    {
        id: "2",
        action: "New critical vulnerability detected",
        entityType: "vulnerability",
        entityName: "CVE-2024-3400",
        userName: "System",
        timestamp: new Date(Date.now() - 1000 * 60 * 15),
    },
    {
        id: "3",
        action: "Asset added",
        entityType: "asset",
        entityName: "gcp-vm-analytics-03",
        userName: "Mike Johnson",
        timestamp: new Date(Date.now() - 1000 * 60 * 32),
    },
    {
        id: "4",
        action: "Compliance control updated",
        entityType: "compliance",
        entityName: "A.12.6.1 - Technical Vulnerabilities",
        userName: "Lisa Park",
        timestamp: new Date(Date.now() - 1000 * 60 * 48),
    },
    {
        id: "5",
        action: "Scan completed",
        entityType: "scan",
        entityName: "Weekly Nessus Scan",
        userName: "System",
        timestamp: new Date(Date.now() - 1000 * 60 * 60),
    },
    {
        id: "6",
        action: "Risk score recalculated",
        entityType: "risk",
        entityName: "Organization Risk Assessment",
        userName: "System",
        timestamp: new Date(Date.now() - 1000 * 60 * 90),
    },
];

export const mockExploitedVulnerabilities: ExploitedVulnerability[] = [
    {
        id: "1",
        cveId: "CVE-2024-3400",
        title: "Palo Alto Networks PAN-OS Command Injection",
        severity: "CRITICAL",
        epssScore: 0.97,
        affectedAssets: 12,
        cisaKev: true,
        exploitMaturity: "HIGH",
    },
    {
        id: "2",
        cveId: "CVE-2024-21762",
        title: "Fortinet FortiOS Out-of-bounds Write",
        severity: "CRITICAL",
        epssScore: 0.94,
        affectedAssets: 8,
        cisaKev: true,
        exploitMaturity: "HIGH",
    },
    {
        id: "3",
        cveId: "CVE-2024-1709",
        title: "ConnectWise ScreenConnect Authentication Bypass",
        severity: "CRITICAL",
        epssScore: 0.91,
        affectedAssets: 5,
        cisaKev: true,
        exploitMaturity: "FUNCTIONAL",
    },
    {
        id: "4",
        cveId: "CVE-2023-46805",
        title: "Ivanti Connect Secure Authentication Bypass",
        severity: "HIGH",
        epssScore: 0.89,
        affectedAssets: 14,
        cisaKev: true,
        exploitMaturity: "HIGH",
    },
    {
        id: "5",
        cveId: "CVE-2024-27198",
        title: "JetBrains TeamCity Authentication Bypass",
        severity: "CRITICAL",
        epssScore: 0.87,
        affectedAssets: 3,
        cisaKev: true,
        exploitMaturity: "FUNCTIONAL",
    },
];

export const mockAssets: Asset[] = [
    {
        id: "1",
        name: "prod-db-master-01",
        type: "DATABASE",
        hostname: "db-master-01.prod.internal",
        ipAddress: "10.0.1.50",
        operatingSystem: "Ubuntu 22.04 LTS",
        environment: "PRODUCTION",
        criticality: "CRITICAL",
        status: "ACTIVE",
        owner: "Database Team",
        department: "Engineering",
        tags: ["mysql", "primary", "tier-1"],
        lastSeen: new Date(Date.now() - 1000 * 60 * 2),
        createdAt: new Date("2023-06-15"),
        vulnerabilityCount: 47,
    },
    {
        id: "2",
        name: "api-gateway-prod",
        type: "APPLICATION",
        hostname: "api-gateway.prod.internal",
        ipAddress: "10.0.2.10",
        operatingSystem: "Container (Alpine)",
        environment: "PRODUCTION",
        criticality: "CRITICAL",
        status: "ACTIVE",
        owner: "Platform Team",
        department: "Engineering",
        tags: ["kong", "api", "external-facing"],
        lastSeen: new Date(Date.now() - 1000 * 60 * 1),
        createdAt: new Date("2023-03-20"),
        vulnerabilityCount: 38,
    },
    {
        id: "3",
        name: "aws-ec2-payments",
        type: "CLOUD_INSTANCE",
        hostname: "payments-service.aws",
        ipAddress: "172.31.45.120",
        operatingSystem: "Amazon Linux 2023",
        environment: "PRODUCTION",
        criticality: "CRITICAL",
        status: "ACTIVE",
        owner: "Payments Team",
        department: "Finance",
        cloudProvider: "AWS",
        tags: ["pci", "payments", "tier-1"],
        lastSeen: new Date(Date.now() - 1000 * 60 * 5),
        createdAt: new Date("2023-08-10"),
        vulnerabilityCount: 52,
    },
    {
        id: "4",
        name: "k8s-node-prod-12",
        type: "CONTAINER",
        hostname: "node-12.k8s.internal",
        ipAddress: "10.0.10.112",
        operatingSystem: "Container-Optimized OS",
        environment: "PRODUCTION",
        criticality: "HIGH",
        status: "ACTIVE",
        owner: "DevOps Team",
        department: "Engineering",
        cloudProvider: "GCP",
        tags: ["kubernetes", "worker-node"],
        lastSeen: new Date(Date.now() - 1000 * 60 * 3),
        createdAt: new Date("2023-11-05"),
        vulnerabilityCount: 29,
    },
    {
        id: "5",
        name: "dc1-fw-core-01",
        type: "NETWORK_DEVICE",
        hostname: "fw-core-01.dc1",
        ipAddress: "10.0.0.1",
        operatingSystem: "PAN-OS 11.1",
        environment: "PRODUCTION",
        criticality: "HIGH",
        status: "ACTIVE",
        owner: "Network Team",
        department: "IT",
        tags: ["firewall", "palo-alto", "perimeter"],
        lastSeen: new Date(Date.now() - 1000 * 60 * 1),
        createdAt: new Date("2022-12-01"),
        vulnerabilityCount: 18,
    },
];

export const mockVulnerabilities: Vulnerability[] = [
    {
        id: "1",
        cveId: "CVE-2024-3400",
        title: "Palo Alto Networks PAN-OS Command Injection Vulnerability",
        description:
            "A command injection vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS software enables an unauthenticated attacker to execute arbitrary code with root privileges on the firewall.",
        severity: "CRITICAL",
        cvssScore: 10.0,
        cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        epssScore: 0.97,
        epssPercentile: 99.9,
        isExploited: true,
        exploitMaturity: "HIGH",
        cisaKev: true,
        source: "NESSUS",
        status: "OPEN",
        solution: "Upgrade to PAN-OS 10.2.9-h1, 11.0.4-h1, 11.1.2-h3, or later.",
        riskScore: 98.5,
        affectedAssets: 12,
        firstDetected: new Date("2024-04-12"),
        lastSeen: new Date(Date.now() - 1000 * 60 * 60),
    },
    {
        id: "2",
        cveId: "CVE-2024-21762",
        title: "Fortinet FortiOS Out-of-bounds Write Vulnerability",
        description:
            "A out-of-bounds write vulnerability in FortiOS SSL VPN may allow a remote unauthenticated attacker to execute arbitrary code or command via specially crafted HTTP requests.",
        severity: "CRITICAL",
        cvssScore: 9.8,
        cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        epssScore: 0.94,
        epssPercentile: 99.8,
        isExploited: true,
        exploitMaturity: "HIGH",
        cisaKev: true,
        source: "OPENVAS",
        status: "IN_PROGRESS",
        solution: "Upgrade to FortiOS 7.4.3, 7.2.7, 7.0.14, 6.4.15, or later.",
        riskScore: 96.2,
        affectedAssets: 8,
        firstDetected: new Date("2024-02-08"),
        lastSeen: new Date(Date.now() - 1000 * 60 * 30),
    },
    {
        id: "3",
        cveId: "CVE-2024-1709",
        title: "ConnectWise ScreenConnect Authentication Bypass",
        description:
            "An authentication bypass vulnerability exists in ConnectWise ScreenConnect 23.9.7 and prior. This could allow an attacker direct access without proper credentials.",
        severity: "CRITICAL",
        cvssScore: 10.0,
        cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
        epssScore: 0.91,
        epssPercentile: 99.5,
        isExploited: true,
        exploitMaturity: "FUNCTIONAL",
        cisaKev: true,
        source: "QUALYS",
        status: "OPEN",
        solution: "Update ScreenConnect to version 23.9.8 or later.",
        riskScore: 94.8,
        affectedAssets: 5,
        firstDetected: new Date("2024-02-19"),
        lastSeen: new Date(Date.now() - 1000 * 60 * 45),
    },
    {
        id: "4",
        cveId: "CVE-2023-48788",
        title: "Fortinet FortiClientEMS SQL Injection",
        description:
            "An improper neutralization of special elements used in an SQL command vulnerability in FortiClientEMS allows attacker to execute unauthorized code via specially crafted packets.",
        severity: "HIGH",
        cvssScore: 9.3,
        cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
        epssScore: 0.72,
        epssPercentile: 98.2,
        isExploited: false,
        exploitMaturity: "POC",
        cisaKev: false,
        source: "NESSUS",
        status: "OPEN",
        solution: "Apply vendor patch or upgrade to latest version.",
        riskScore: 82.4,
        affectedAssets: 15,
        firstDetected: new Date("2024-03-12"),
        lastSeen: new Date(Date.now() - 1000 * 60 * 120),
    },
    {
        id: "5",
        cveId: "CVE-2024-0012",
        title: "Palo Alto Networks PAN-OS Authentication Bypass",
        description:
            "An authentication bypass in the management web interface of PAN-OS allows an unauthenticated attacker with network access to the management web interface to gain administrator privileges.",
        severity: "CRITICAL",
        cvssScore: 9.8,
        cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
        epssScore: 0.95,
        epssPercentile: 99.7,
        isExploited: true,
        exploitMaturity: "HIGH",
        cisaKev: true,
        source: "RAPID7",
        status: "MITIGATED",
        solution: "Restrict access to management interface and apply emergency patch.",
        riskScore: 92.1,
        affectedAssets: 6,
        firstDetected: new Date("2024-11-18"),
        lastSeen: new Date(Date.now() - 1000 * 60 * 15),
    },
];

// Asset type distribution for charts
export const mockAssetTypeDistribution = [
    { type: "SERVER", count: 342, percentage: 27.4 },
    { type: "CLOUD_INSTANCE", count: 285, percentage: 22.9 },
    { type: "CONTAINER", count: 256, percentage: 20.5 },
    { type: "APPLICATION", count: 198, percentage: 15.9 },
    { type: "NETWORK_DEVICE", count: 89, percentage: 7.1 },
    { type: "DATABASE", count: 45, percentage: 3.6 },
    { type: "OTHER", count: 32, percentage: 2.6 },
];

// Vulnerability sources for charts
export const mockVulnSourceDistribution = [
    { source: "NESSUS", count: 1542 },
    { source: "TRIVY", count: 987 },
    { source: "OPENVAS", count: 654 },
    { source: "QUALYS", count: 421 },
    { source: "MANUAL", count: 238 },
];

// Monthly remediation trends
export const mockRemediationTrends = [
    { month: "Aug", opened: 425, closed: 312, net: -113 },
    { month: "Sep", opened: 398, closed: 356, net: -42 },
    { month: "Oct", opened: 456, closed: 401, net: -55 },
    { month: "Nov", opened: 512, closed: 478, net: -34 },
    { month: "Dec", opened: 387, closed: 395, net: 8 },
    { month: "Jan", opened: 342, closed: 312, net: -30 },
];
