version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: secyourflow-db
    restart: unless-stopped
    env_file: ./env/db.env
    volumes:
      - secyourflow_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: secyourflow:latest
    container_name: secyourflow-app
    restart: unless-stopped
    env_file: ./env/secyourflow.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  secyourflow_db_data:
